### ISSUE TITLE
Snap didn't work properly 

### ISSUE THREAD

**Issue by Rifqi22** [gislayer/mapbox-gl-snap#1]
Ive tried the snap and it work perfectly when i use the origin button draw from maplibre itself. But when i start the draw using custom button, it didn't work properly

As you can see below, when i try to start draw using my custom button the snap is not working unless i finish my drawing then the snap is just started. But when i draw from maplibre button it works perfectly
 (url)
![snap_problem](https://github.com/user-attachments/assets/2b9c5517-6812-4088-8f85-b4c51d3cd41d)

**Comment by gislayer** [comment]
![image](https://github.com/user-attachments/assets/536a0ad9-f7ef-4757-ad71-e5544cd2cbef)

Could you try below code ?

`mapboxSnap.status=true;`

**Comment by Rifqi22** [comment]
wow thanks it now works perfectly!

FYI if you want to activate snapping feature using custom button draw mode, dont forget to remove "snap-helper-circle" layer first then remove "snap-helper-circle" source before re adding mapboxSnapDraw instance. Because if you don't, it will raise an error suggesting that "snap-helper-circle" is already found. Hopefully this will help!

    const handleStartDraw = useCallback(() => {
    // Check and delete the layer 
      if (map.getLayer("snap-helper-circle")) {
        console.log("Snap circle layer found, deleting layer");
        map.removeLayer("snap-helper-circle");
      }
     // Check and delete the source
      if (map.getSource("snap-helper-circle")) {
        console.log("Snap circle srouce found, deleting source");
        map.removeSource("snap-helper-circle");
        console.log("update layer:", map.getStyle().layers);
      }
      const mapboxSnap = new MapboxSnap({
        map: map,
        drawing: draw,
        options: {
          layers: [
            "profilerw", // Your custom layer
            "gl-draw-line-inactive.cold",
            "gl-draw-line-active.cold",
            "gl-draw-line-static.cold",
            "gl-draw-line-inactive.hot",
            "gl-draw-line-active.hot",
            "gl-draw-line-static.hot",
          ],
          radius: 20, // Snap radius in pixels
          rules: ["vertex", "midpoint", "edge"], // Snap rules
        },
        status: true,
      });
      if (kategori?.tipe === "Point") {
        draw.changeMode("draw_point");
      } else if (kategori?.tipe === "Polyline") {
        draw.changeMode("draw_line_string");
      }
      // Change to satellite basemap
      const satelliteBasemap = basemapList?.find(
        (el) => el.basemap_name === "Google Satelite"
      );
      if (satelliteBasemap) {
        let currentStyle = map.getStyle();
        currentStyle.sources["raster-tiles"] = {
          type: "raster",
          tiles: [satelliteBasemap.tile_url],
          tileSize: 256,
        };
        map.setStyle(currentStyle);
      }
      map.setPaintProperty("profilerw", "fill-opacity", 0);
    }, [draw, kategori, map, basemapList]);

**Comment by Rifqi22** [comment]
And this is the best snap package i have found this far! thank you @gislayer
